version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "./kafka_data:/bitnami"
    env_file:
      - .env
    depends_on:
      - zookeeper
  mysql:
    image: mysql:8.0.4
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env
  mongodb:
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    env_file:
      - .env
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  bankingNetwork:
    external: true
